### ISSUE TITLE
No pth file

### ISSUE THREAD

**Issue by mszlosser** [xg416/TMT#1]
FileNotFoundError: [Errno 2] No such file or directory: './model_zoo/shuffle_MS_video.pth'

**Comment by xg416** [comment]
Hi, we will release the .pth file and data upon acceptance, perhaps before acceptance, if we configure the port for public access earlier.

**Comment by mszlosser** [comment]
OK, thanks

**Comment by CongliWANG** [comment]
May I ask what is the latest plan regarding a full code release?  Many thanks.
