### ISSUE TITLE
how to generat the "dynamic scenes" video files in the training dataset?

### ISSUE THREAD

**Issue by phoenixhuawei** [xg416/TMT#10]
Hi, Thank you for sharing the fantastic models!

Could you please explain how the "dynamic scenes" video files in the training dataset are generated?
When I attempting to create my own dataset using  [TurbulenceSim_P2S](https://github.itap.purdue.edu/StanleyChanGroup/TurbulenceSim_P2S)，I found that I couldn't achieve the same effects as in the reference data, The turbulent effects between the video frames are independent and lack coherence, unlike the natural flow seen in the reference data.

Thank you very much~

**Comment by xg416** [comment]
Please review the data synthesis part in both this paper and https://ieeexplore.ieee.org/abstract/document/9969142/.
https://github.itap.purdue.edu/StanleyChanGroup/TurbulenceSim_P2S is out of date. We provided guidance in those papers to upgrade the old simulator to a newer version. If you want to use the newest simulator developed by us, please contact Dr. Chan directly.
