### ISSUE TITLE
Current Code Cannot Run

### ISSUE THREAD

**Issue by codingrex** [xg416/TMT#12]
Hi, 

Thanks very much for your code. 

I tried to run your code, but it cannot be run. 
I think maybe you upload the wrong version of the files, can you double-check them? 
Examples:
 If I want to run [test_TMT_static.py](https://github.com/xg416/TMT/blob/main/code/test_TMT_static.py)
1) In the import 
there is no "utils_image.py" in utils folder, only "utils_images.py"
[line](https://github.com/xg416/TMT/blob/b87e18ca38cc0a930ed425995c97f53a3b393b00/code/test_TMT_static.py#L11)

2) In the import: 
Also there is no "TMT_MS.py" in model folder, even if I change it to "from model.TMT import TMT_MS", this version of model architecture does not meet your uploaded checkpoints (cannot load model) 
[line](https://github.com/xg416/TMT/blob/b87e18ca38cc0a930ed425995c97f53a3b393b00/code/test_TMT_static.py#L9)

**Comment by xg416** [comment]
Hi,

Thanks for raising the issue! For the 1st point, I've renamed utils_images.py to utils_image.py; for the 2nd point, it is caused by the old naming convention and slightly different configuration. I have updated the test_TMT_static.py file and the old model file for temporary testing, and will update it to the standard model soon.

**Comment by codingrex** [comment]
Thanks for replying. It fixed the problems mentioned above. 

However, why I run to run [test_TMT_dynamic.py](https://github.com/xg416/TMT/blob/main/code/train_TMT_dynamic.py). I also cannot load in the model. 

The same reason: No TMT_MS.py, even if I changed to TMT_old.py or TMT.py, model mismatched. 

Can you check that as well.

**Comment by xg416** [comment]
Hi, yes you should change to TMT.py, I have tested it with the following code and it shows the weight is loaded correctly:
```
import torch
from model.TMT import TMT_MS
model = TMT_MS(num_blocks=[2,3,3,4], num_refinement_blocks=2, n_frames=12, att_type='shuffle').cuda()
checkpoint = torch.load("../../TMT_dynamic.pth")
model.load_state_dict(checkpoint['state_dict'] if 'state_dict' in checkpoint.keys() else checkpoint)
```
