### ISSUE TITLE
Issue with TMT_static.pth Pre-trained Model Loading

### ISSUE THREAD

**Issue by chennanST** [xg416/TMT#13]
Hi,

I hope you're doing well. Recently, I came across your "TMT" project on GitHub and found it incredibly insightful. However, while exploring the codebase, I noticed an issue regarding the usage of the pre-trained models you provided.

Specifically, when attempting to use TMT_static.pth, I encountered the following error:

```
size mismatch for down1_2.body.0.weight: copying a param with shape torch.Size([24, 48, 3, 3, 3]) from checkpoint, the shape in the current model is torch.Size([12, 48, 3, 3, 3]).
size mismatch for down2_3.body.0.weight: copying a param with shape torch.Size([48, 96, 3, 3, 3]) from checkpoint, the shape in the current model is torch.Size([36, 96, 3, 3, 3]).
```

However, it's worth noting that I've successfully used the other three pre-trained models without encountering any issues.

Furthermore, I found that replacing TMT.py with TMT_old.py resolves the problem, indicating a potential discrepancy in model architecture or parameter initialization between TMT.py and TMT_old.py.

Would you mind investigating this matter further? It seems there might be a mismatch in model architecture or parameter initialization between the pre-trained model and the current codebase. Revisiting the model definition or the parameters of the pre-trained model could potentially resolve this inconsistency.

If you need any additional information or assistance from my side, please feel free to reach out. 

Thank you for your attention to this matter and your dedication to maintaining the project's quality.

Best regards

**Comment by xg416** [comment]
Hi, thanks for pointing this out. 
I assume that you came across this problem when running video_inference.py. It is not recommended to try the static model for this. Note that our final model is the 2-stage model, the one-stage model is an intermediate product. Although it is very easy to use, we didn't update the one-stage static checkpoint before.
However, we still updated the one-stage static checkpoint, now all models share the same architecture. Can you download the new checkpoint and try it?

**Comment by chennanST** [comment]
Hi,

Thank you for your prompt response and clarification regarding the issue. I appreciate your explanation regarding the use of the static model and the distinction between the one-stage and two-stage models.

I will download the updated one-stage static checkpoint as per your suggestion and give it a try. I'm glad to hear that all models now share the same architecture, which should help streamline the usage process.

Once again, thank you for your attention to this matter and for providing the updated checkpoint. I will let you know if I encounter any further issues or if everything works smoothly with the new checkpoint.

Best regards.

**Comment by xg416** [comment]
No problem, thanks for your attention to this work!
