### ISSUE TITLE
Query Regarding Discrepancies Between Model Files and Post-Training Procedures

### ISSUE THREAD

**Issue by chennanST** [xg416/TMT#14]
"Hello, I hope this message finds you well. After training the tilt model using train_tilt_static.py, I obtained the model_best.pth file, which has a size of 24,969kb. However, I noticed that the static_1st_stage.pth file provided by you is significantly smaller, at 8,330kb. It's evident that there are differences between these two sets of parameters. Moreover, I observed that static_1st_stage.pth contains complete parameter types, whereas I couldn't ascertain the parameter types of model_best.pth. Could you please clarify the reason behind this? Additionally, I would like to inquire if there are any further steps or operations needed to be performed on model_best.pth after running train_tilt_static.py. Your guidance on this matter would be greatly appreciated. Thank you for your time and assistance."

**Comment by xg416** [comment]
Hi, the checkpoint you save during training has the gradient information from the optimizer, which is useless for inference. The model static_1st_stage.pth only contains the weight.

**Comment by JhonsonLT** [comment]
Thanks for replying. It fixed the problems mentioned above.

**Comment by chennanST** [comment]
Thanks for replying. It fixed the problems mentioned above.
