### ISSUE TITLE
Directory Issue

### ISSUE THREAD

**Issue by MZeeshanAnjum** [xg416/TMT#15]
'D:\\Study\\FYP\\final_test\\scene_0001\\turb\\0.jpg'

I gave the data path directory as: 
'D:\\Study\\FYP\\final_test'

**Comment by xg416** [comment]
Sorry I do not get the issue. Could you provide more details?

**Comment by MZeeshanAnjum** [comment]
The directories were hard coded in the code, but i figured it out!
Thank You for you reply!!
Appreciated

**Comment by MZeeshanAnjum** [comment]
Got it
