### ISSUE TITLE
RT_warp is missing

### ISSUE THREAD

**Issue by mzalaki00** [xg416/TMT#6]
when i wanted to test script test_model_static with TMT_static.pth give a error "name 'RT_warp' is not defined"
how to fix that?

second question when to use static model? static here means fixed camera or sth else?
and dynamic means dynamic scene?

**Comment by xg416** [comment]
According to our paper, the static scene means the scene you are capturing is static, please refer to "Results on real world static image sequences" in https://xg416.github.io/TMT/. It is the default setting for most traditional turbulence mitigation methods.

**Comment by xg416** [comment]
To test the static scene model, please still use video_sequence.py. You can use TMT_static.pth for this.
