### ISSUE TITLE
Pre-trained models with training epochs, iterations, and optimizer states

### ISSUE THREAD

**Issue by Shengqi77** [xg416/TMT#9]
Hello Dr. Zhang！
I'm attempting to use your pre-trained models for training, but I've noticed that the model file doesn't contain information such as epochs, iterations, and optimizer states. Would it be possible for you to release pre-trained models that includes above information.
Thank you once again for generously releasing the code and models！
![123](https://github.com/xg416/TMT/assets/129826877/7f1b1b4f-2040-4e04-a053-5aa2b2e4f946)

**Comment by xg416** [comment]
Hi, the number of iterations should be 800,000. If you would like to fine-tune the model on your own dataset, you can just comment out the optimizer.load_state_dict(). Currently my Google Drive does not have enough space to put optimizer status.

**Comment by Shengqi77** [comment]
Ok，thanks！
